# Generated by Django 2.1.5 on 2019-01-16 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('soundfile', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='pinpoint',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.County'),
        ),
        migrations.AddField(
            model_name='county',
            name='region',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='frontend.Region'),
            preserve_default=False,
        ),
    ]
